const mapstyle = {
  version: 8,
  name: 'Positron',
  metadata: {
    'mapbox:autocomposite': false,
    'mapbox:type': 'template',
    'mapbox:groups': {
      b6371a3f2f5a9932464fa3867530a2e5: {
        name: 'Transportation',
        collapsed: false,
      },
      a14c9607bc7954ba1df7205bf660433f: { name: 'Boundaries' },
      '101da9f13b64a08fa4b6ac1168e89e5f': { name: 'Places', collapsed: false },
    },
    'openmaptiles:version': '3.x',
    'openmaptiles:mapbox:owner': 'openmaptiles',
    'openmaptiles:mapbox:source:url': 'mapbox://openmaptiles.4qljc88t',
    'maputnik:renderer': 'mbgljs',
  },
  sources: {
    openmaptiles: {
      type: 'vector',
      tiles: ['https://cdn.ons.gov.uk/maptiles/osm/v2/{z}/{x}/{y}.pbf'],
      buffer: 0,
      minzoom: 0,
      maxzoom: 14,
      attribution:
        '<a href="https://www.openstreetmap.org" target="_blank">&copy; OpenStreetMap</a>',
    },
  },
  sprite: 'https://cdn.ons.gov.uk/maptiles/osm/spritesv1/sprite',
  glyphs: 'https://cdn.ons.gov.uk/maptiles/osm/fontsv1/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': '#BFBFBF' },
    },
    {
      id: 'landcover-glacier',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849388993.3071' },
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'subclass', 'glacier'],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': '#ffffff',
        'fill-opacity': {
          base: 1,
          stops: [
            [0, 0.9],
            [10, 0.3],
          ],
        },
      },
    },
    {
      id: 'landuse-commercial',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849388993.3071' },
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['==', 'class', 'commercial'],
      ],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': '#7F7F7F' },
    },
    {
      id: 'landuse-industrial',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: [
        'all',
        ['==', '$type', 'Polygon'],
        ['in', 'class', 'industrial', 'garages', 'dam'],
      ],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': '#7F7F7F' },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['==', '$type', 'LineString'],
      layout: { visibility: 'visible' },
      paint: { 'line-color': '#BFDCEE' },
    },
    {
      id: 'water-offset',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849382550.77' },
      source: 'openmaptiles',
      'source-layer': 'water',
      maxzoom: 8,
      filter: ['==', '$type', 'Polygon'],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': '#BFDCEE',
        'fill-opacity': 1,
        'fill-translate': {
          base: 1,
          stops: [
            [6, [2, 0]],
            [8, [0, 0]],
          ],
        },
      },
    },
    {
      id: 'water',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849382550.77' },
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all', ['!=', 'intermittent', 1], ['!=', 'brunnel', 'tunnel']],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': '#BFDCEE' },
    },
    {
      id: 'water-intermittent',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849382550.77' },
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all', ['==', 'intermittent', 1]],
      layout: { visibility: 'visible' },
      paint: { 'fill-color': '#BFDCEE', 'fill-opacity': 0.7 },
    },
    {
      id: 'water-pattern',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849382550.77' },
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['all'],
      layout: { visibility: 'visible' },
      paint: { 'fill-pattern': 'wave', 'fill-translate': [0, 2.5] },
    },
    {
      id: 'landcover-ice-shelf',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849382550.77' },
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'subclass', 'ice_shelf'],
      layout: { visibility: 'visible' },
      paint: {
        'fill-color': '#fff',
        'fill-opacity': {
          base: 1,
          stops: [
            [0, 0.9],
            [10, 0.3],
          ],
        },
      },
    },
    {
      id: 'tunnel-service-track-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'service', 'track'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [0.5, 0.25],
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1],
            [16, 4],
            [20, 11],
          ],
        },
      },
    },
    {
      id: 'tunnel-motorway-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round', visibility: 'visible' },
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [0.5, 0.25],
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 15],
          ],
        },
      },
    },
    {
      id: 'tunnel-minor-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'minor']],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [12, 0],
            [12.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [12, 0.5],
            [13, 1],
            [14, 4],
            [20, 15],
          ],
        },
        'line-dasharray': [0.5, 0.25],
      },
    },
    {
      id: 'tunnel-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 15],
          ],
        },
        'line-dasharray': [0.5, 0.25],
      },
    },
    {
      id: 'tunnel-secondary-tertiary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [20, 17],
          ],
        },
        'line-dasharray': [0.5, 0.25],
      },
    },
    {
      id: 'tunnel-trunk-primary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'primary', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0.4],
            [6, 0.6],
            [7, 1.5],
            [20, 22],
          ],
        },
      },
    },
    {
      id: 'tunnel-motorway-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round', visibility: 'visible' },
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [0.5, 0.25],
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0.4],
            [6, 0.6],
            [7, 1.5],
            [20, 22],
          ],
        },
      },
    },
    {
      id: 'tunnel-path',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'path'],
      ],
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [1.5, 0.75],
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1.2],
            [20, 4],
          ],
        },
      },
    },
    {
      id: 'tunnel-motorway-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round', visibility: 'visible' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'tunnel-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'tunnel-minor',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'minor']],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [13.5, 0],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'tunnel-secondary-tertiary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 10],
          ],
        },
      },
    },
    {
      id: 'tunnel-trunk-primary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['in', 'class', 'primary', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'tunnel-motorway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round', visibility: 'visible' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'tunnel-railway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849354174.1904' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'tunnel'], ['==', 'class', 'rail']],
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [2, 2],
        'line-width': {
          base: 1.4,
          stops: [
            [14, 0.4],
            [15, 0.75],
            [20, 2],
          ],
        },
      },
    },
    {
      id: 'road_area_pier',
      type: 'fill',
      metadata: {},
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', '$type', 'Polygon'], ['==', 'class', 'pier']],
      layout: { visibility: 'visible' },
      paint: { 'fill-antialias': true, 'fill-color': '#F37788' },
    },
    {
      id: 'road_pier',
      type: 'line',
      metadata: {},
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', '$type', 'LineString'], ['in', 'class', 'pier']],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1],
            [17, 4],
          ],
        },
      },
    },
    {
      id: 'highway-area',
      type: 'fill',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', '$type', 'Polygon'], ['!in', 'class', 'pier']],
      layout: { visibility: 'visible' },
      paint: {
        'fill-antialias': false,
        'fill-color': '#F37788',
        'fill-opacity': 0.9,
        'fill-outline-color': '#F37788',
      },
    },
    {
      id: 'highway-motorway-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 15],
          ],
        },
      },
    },
    {
      id: 'highway-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 15],
          ],
        },
      },
    },
    {
      id: 'highway-minor-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!=', 'brunnel', 'tunnel'],
        ['in', 'class', 'minor', 'service', 'track'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [12, 0],
            [12.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [12, 0.5],
            [13, 1],
            [14, 4],
            [20, 15],
          ],
        },
      },
    },
    {
      id: 'highway-secondary-tertiary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [8, 1.5],
            [20, 17],
          ],
        },
      },
    },
    {
      id: 'highway-primary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'primary'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [7, 0],
            [8, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [7, 0],
            [8, 0.6],
            [9, 1.5],
            [20, 22],
          ],
        },
      },
    },
    {
      id: 'highway-trunk-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [5, 0],
            [6, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0],
            [6, 0.6],
            [7, 1.5],
            [20, 22],
          ],
        },
      },
    },
    {
      id: 'highway-motorway-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 4,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [4, 0],
            [5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [4, 0],
            [5, 0.4],
            [6, 0.6],
            [7, 1.5],
            [20, 22],
          ],
        },
      },
    },
    {
      id: 'highway-path',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'path'],
      ],
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [1.5, 0.75],
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1.2],
            [20, 4],
          ],
        },
      },
    },
    {
      id: 'highway-motorway-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'highway-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'highway-minor',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!=', 'brunnel', 'tunnel'],
        ['in', 'class', 'minor', 'service', 'track'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [13.5, 0],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'highway-secondary-tertiary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [8, 0.5],
            [20, 13],
          ],
        },
      },
    },
    {
      id: 'highway-primary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'primary'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [8.5, 0],
            [9, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'highway-trunk',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['in', 'class', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'highway-motorway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 5,
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'railway-transit',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'transit'],
        ['!in', 'brunnel', 'tunnel'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#FBF040',
        'line-width': {
          base: 1.4,
          stops: [
            [14, 0.4],
            [20, 1],
          ],
        },
      },
    },
    {
      id: 'railway-transit-hatching',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'transit'],
        ['!in', 'brunnel', 'tunnel'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#FBF040',
        'line-dasharray': [0.2, 8],
        'line-width': {
          base: 1.4,
          stops: [
            [14.5, 0],
            [15, 2],
            [20, 6],
          ],
        },
      },
    },
    {
      id: 'railway-service',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'rail'],
        ['has', 'service'],
      ],
      paint: {
        'line-color': '#FBF040',
        'line-width': {
          base: 1.4,
          stops: [
            [14, 0.4],
            [20, 1],
          ],
        },
      },
    },
    {
      id: 'railway-service-hatching',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'class', 'rail'],
        ['has', 'service'],
      ],
      layout: { visibility: 'visible' },
      paint: {
        'line-color': '#FBF040',
        'line-dasharray': [0.2, 8],
        'line-width': {
          base: 1.4,
          stops: [
            [14.5, 0],
            [15, 2],
            [20, 6],
          ],
        },
      },
    },
    {
      id: 'railway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!has', 'service'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'rail'],
      ],
      paint: {
        'line-color': '#FBF040',
        'line-width': {
          base: 1.4,
          stops: [
            [14, 0.4],
            [15, 0.75],
            [20, 2],
          ],
        },
      },
    },
    {
      id: 'railway-hatching',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['!has', 'service'],
        ['!in', 'brunnel', 'bridge', 'tunnel'],
        ['==', 'class', 'rail'],
      ],
      paint: {
        'line-color': '#FBF040',
        'line-dasharray': [0.2, 8],
        'line-width': {
          base: 1.4,
          stops: [
            [14.5, 0],
            [15, 3],
            [20, 8],
          ],
        },
      },
    },
    {
      id: 'bridge-motorway-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 19],
          ],
        },
      },
    },
    {
      id: 'bridge-link-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [12, 1],
            [13, 3],
            [14, 4],
            [20, 19],
          ],
        },
      },
    },
    {
      id: 'bridge-secondary-tertiary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0.4],
            [7, 0.6],
            [8, 1.5],
            [20, 21],
          ],
        },
      },
    },
    {
      id: 'bridge-trunk-primary-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'primary', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0.4],
            [6, 0.6],
            [7, 1.5],
            [20, 26],
          ],
        },
      },
    },
    {
      id: 'bridge-motorway-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [5, 0.4],
            [6, 0.6],
            [7, 1.5],
            [20, 26],
          ],
        },
      },
    },
    {
      id: 'bridge-minor-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'minor', 'service', 'track'],
      ],
      layout: { 'line-cap': 'butt', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': {
          stops: [
            [12, 0],
            [12.5, 1],
          ],
        },
        'line-width': {
          base: 1.2,
          stops: [
            [12, 0.5],
            [13, 1],
            [14, 6],
            [20, 24],
          ],
        },
      },
    },
    {
      id: 'bridge-path-casing',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'path'],
      ],
      paint: {
        'line-color': '#BFBFBF',
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1.2],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'bridge-path',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'path'],
      ],
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [1.5, 0.75],
        'line-width': {
          base: 1.2,
          stops: [
            [15, 1.2],
            [20, 4],
          ],
        },
      },
    },
    {
      id: 'bridge-motorway-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'motorway'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'bridge-link',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'trunk', 'primary', 'secondary', 'tertiary'],
        ['==', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [12.5, 0],
            [13, 1.5],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'bridge-minor',
      type: 'line',
      metadata: { 'mapbox:group': '1444849345966.4436' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', '$type', 'LineString'],
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'minor', 'service', 'track'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-opacity': 1,
        'line-width': {
          base: 1.2,
          stops: [
            [13.5, 0],
            [14, 2.5],
            [20, 11.5],
          ],
        },
      },
    },
    {
      id: 'bridge-secondary-tertiary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'secondary', 'tertiary'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [8, 0.5],
            [20, 13],
          ],
        },
      },
    },
    {
      id: 'bridge-trunk-primary',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['in', 'class', 'primary', 'trunk'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'bridge-motorway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['==', 'brunnel', 'bridge'],
        ['==', 'class', 'motorway'],
        ['!=', 'ramp', 1],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.2,
          stops: [
            [6.5, 0],
            [7, 0.5],
            [20, 18],
          ],
        },
      },
    },
    {
      id: 'bridge-railway',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['==', 'class', 'rail']],
      paint: {
        'line-color': '#F37788',
        'line-width': {
          base: 1.4,
          stops: [
            [14, 0.4],
            [15, 0.75],
            [20, 2],
          ],
        },
      },
    },
    {
      id: 'bridge-railway-hatching',
      type: 'line',
      metadata: { 'mapbox:group': '1444849334699.1902' },
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['all', ['==', 'brunnel', 'bridge'], ['==', 'class', 'rail']],
      paint: {
        'line-color': '#F37788',
        'line-dasharray': [0.2, 8],
        'line-width': {
          base: 1.4,
          stops: [
            [14.5, 0],
            [15, 3],
            [20, 8],
          ],
        },
      },
    },
    {
      id: 'boundary-land-level-4',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      minzoom: 2,
      filter: [
        'all',
        ['>=', 'admin_level', 3],
        ['<=', 'admin_level', 8],
        ['!=', 'maritime', 1],
      ],
      layout: { 'line-join': 'round', visibility: 'visible' },
      paint: {
        'line-color': '#FFFFFF',
        'line-dasharray': [3, 1, 1, 1],
        'line-width': {
          base: 1.4,
          stops: [
            [4, 0.4],
            [5, 1],
            [12, 3],
          ],
        },
      },
    },
    {
      id: 'boundary-land-level-2',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: [
        'all',
        ['==', 'admin_level', 2],
        ['!=', 'maritime', 1],
        ['!=', 'disputed', 1],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': {
          base: 1,
          stops: [
            [0, 0.6],
            [4, 1.4],
            [5, 2],
            [12, 8],
          ],
        },
      },
    },
    {
      id: 'boundary-land-disputed',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['all', ['!=', 'maritime', 1], ['==', 'disputed', 1]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        visibility: 'visible',
      },
      paint: {
        'line-color': '#FFFFFF',
        'line-dasharray': [1, 3],
        'line-width': {
          base: 1,
          stops: [
            [0, 0.6],
            [4, 1.4],
            [5, 2],
            [12, 8],
          ],
        },
      },
    },
    {
      id: 'place-town',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', 'class', 'town'],
      layout: {
        'text-size': 10,
        'icon-image': {
          base: 1,
          stops: [
            [0, 'circle-11'],
            [8, ''],
          ],
        },
        'text-transform': 'none',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        visibility: 'visible',
        'text-offset': [0.5, 0.2],
        'icon-size': 0.4,
        'text-anchor': {
          base: 1,
          stops: [
            [0, 'left'],
            [8, 'center'],
          ],
        },
        'text-field': '{name:latin}\n{name:nonlatin}',
      },
      paint: {
        'text-color': '#404040',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place-city',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['all', ['!=', 'capital', 2], ['==', 'class', 'city']],
      layout: {
        'text-size': 10,
        'icon-image': {
          base: 1,
          stops: [
            [0, 'circle-11'],
            [8, ''],
          ],
        },
        'text-transform': 'none',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        visibility: 'visible',
        'text-offset': [0.5, 0.2],
        'icon-size': 0.4,
        'text-anchor': {
          base: 1,
          stops: [
            [0, 'left'],
            [8, 'center'],
          ],
        },
        'text-field': '{name:latin}\n{name:nonlatin}',
      },
      paint: {
        'text-color': '#404040',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place-city-capital',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['all', ['==', 'capital', 2], ['==', 'class', 'city']],
      layout: {
        'text-size': 14,
        'icon-image': {
          base: 1,
          stops: [
            [0, 'star-11'],
            [8, ''],
          ],
        },
        'text-transform': 'none',
        'text-font': ['Noto Sans Regular'],
        'text-justify': 'left',
        visibility: 'visible',
        'text-offset': [0.5, 0.2],
        'icon-size': 1,
        'text-anchor': {
          base: 1,
          stops: [
            [0, 'left'],
            [8, 'center'],
          ],
        },
        'text-field': '{name:latin}\n{name:nonlatin}',
      },
      paint: {
        'text-color': '#404040',
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place-country-other',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'all',
        ['==', 'class', 'country'],
        ['>=', 'rank', 3],
        ['!has', 'iso_a2'],
      ],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['Noto Sans Italic'],
        'text-max-width': 6.25,
        'text-size': {
          stops: [
            [3, 11],
            [7, 17],
          ],
        },
        visibility: 'visible',
      },
      paint: {
        'text-color': '#000',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
      },
    },
    {
      id: 'place-country-3',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'all',
        ['==', 'class', 'country'],
        ['>=', 'rank', 3],
        ['has', 'iso_a2'],
      ],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['Noto Sans Bold'],
        'text-max-width': 6.25,
        'text-size': {
          stops: [
            [3, 11],
            [7, 17],
          ],
        },
        visibility: 'visible',
      },
      paint: {
        'text-color': '#000',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
      },
    },
    {
      id: 'place-country-2',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'all',
        ['==', 'class', 'country'],
        ['==', 'rank', 2],
        ['has', 'iso_a2'],
      ],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['Noto Sans Bold'],
        'text-max-width': 6.25,
        'text-size': {
          stops: [
            [2, 11],
            [5, 17],
          ],
        },
        visibility: 'visible',
      },
      paint: {
        'text-color': '#000',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
      },
    },
    {
      id: 'place-country-1',
      type: 'symbol',
      metadata: { 'mapbox:group': '1444849242106.713' },
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'all',
        ['==', 'class', 'country'],
        ['==', 'rank', 1],
        ['has', 'iso_a2'],
      ],
      layout: {
        'text-field': '{name:latin}',
        'text-font': ['Noto Sans Bold'],
        'text-max-width': 6.25,
        'text-size': {
          stops: [
            [1, 11],
            [4, 17],
          ],
        },
        visibility: 'visible',
      },
      paint: {
        'text-color': '#000',
        'text-halo-blur': 1,
        'text-halo-color': 'rgba(255,255,255,0.8)',
        'text-halo-width': 2,
      },
    },
  ],
  id: 'positron',
};

export default mapstyle;
